title: "Backend Developer"
name: "Jeongeun Lee"
description: "문제를 성능으로 해결하는 백엔드 개발자"
url: "https://lejeongeun.github.io"   # ← 본인 GitHub Pages 주소
baseurl: ""                          # 꼭 빈 값 (username.github.io면)

# ✅ Minimal Mistakes 테마 불러오기
remote_theme: "mmistakes/minimal-mistakes@latest"

# ✅ 스킨 선택
minimal_mistakes_skin: "air"

# ✅ GitHub Pages 호환 플러그인
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# 메뉴 (선택)
include:
  - _pages

# 기본 레이아웃 옵션
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true